- src/page/signin.html
`signin.html` 페이지의 `<head>` 영역에 SEO 관련 메타 태그(`description`, `author`, `robots`) 및 적절한 `<title>`을 추가했습니다. 검색엔진에 노출되지 않아야 하는 페이지이므로 `noindex, nofollow`를 추가했습니다.
resolves #3
> [Feat] main.html SEO 메타태그 및 타이틀 추가

- README.md
- src/common/theme.css
> [Docs] 코딩컨벤션 추가, BreakPoint 추가

- src/components/input.html
- src/components/styles/input.css
- src/page/signin.html
input 컴포넌트의 CSS를 논리 속성 기반으로 리팩토링했습니다.  
기존 UI와 동작에는 변화가 없습니다. 
resolves #8
> [Design] input CSS 논리 속성 적용

- src/common/base.css
- font-size: 1rem
- line-height: 1.75
- color: #111
resolves #16
> [Feat] body 기본 속성 추가

- src/common/index.css
- src/components/style/buttons.css
- button.css => body, div 삭제
- index.css => import button.css 추가
resolves #
> [Modify] button.css , index.css 수정

- src/page/main.html
- src/page/style/main.css
- main.html에 footer.html 자바스크립트와 footer 요소 추가
resolves #27
> [Feat] footer 메인영역에 동적으로 생성되게 추가

- src/components/js/layout.js
- src/page/itemlist.html
- src/page/main.html
- src/page/wishList.html
- main, itemlist, wishList HTML파일에 header,footer 태그 및 layout.js 스크립트 추가
resolves #
> [Feat] Layout JS 추가

- src/components/js/header.js
- src/components/navbar.html
- src/components/style/navbar.css
- z-index 추가
- 키보드 조작 관련 수정
- Side메뉴 ESC입력시 안보이는 기능 추가
resolves #
> [Bug] Header 버그수정

- src/components/style/itemcard.css
container 클래스를 box로 변경
resolves #8
> [Modify] 묶음 클래스명 변경

- src/components/style/wishtitle.css
- src/components/wishtitle.html
위시리스트 페이지 상단 부분을 만들었습니다.
resolves #8
> [Feat] 위시리스트 타이틀 부분 제작

- src/components/itemlist/itemlist-filter.css
- src/components/itemlist/itemlist-header.css
- src/main.js
- src/page/itemlist.html
- src/page/js/itemlist.js
- src/page/style/itemlist.css
- ItemList Page 구현
- 
resolves #
> [Feat] ItemList Page

- src/components/main-page.html
- src/components/style/main-page.css
- [] 새로운 기능 추가
- [] 커밋 메시지 컨벤션에 맞게 작성했습니다.
- [] 코딩 컨벤션에 맞게 작성했습니다.
- [] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트).
resolves #8
> [Feat] 컴포넌트 추가

- index.html
- src/components/common/css/input.css
- src/components/input.html
---
- 인풋 컴포넌트 안에 있던 버튼 요소를 삭제했습니다. 
-인춧 css도 수정해뒀습니다.  
- 중복된 스타일을 제거하고 재사용 가능한 구조로 리팩토링했습니다.  
---
resolves #42
> [Refactor] input요소 정체 정리 밎 겹치는 공용 요소 버튼 삭제

- src/components/style/product-detail-component.css
- src/page/main.html
- src/page/product-detail.html
- src/page/style/product-detail.css
> [Feat] 상품 상세 페이지 추천 상품 추가

- src/components/common/input.html
- src/components/input.html
- src/components/login/login-input.css
- src/components/login/login-input.html
- src/components/style/input.css
- src/page/main.html
- src/page/style/signin.css
- src/page/style/signup.css
- 로그인 레이아웃 UI 마크업 및 스타일 구현
- 잘못 된 경로 링크 수정
resolves #46
> fix: 파일 경로 오류 수정 및 로그인 회윈가입 input등록

- src/components/common/accrodion.html
- src/components/common/buttons.html
- src/components/common/css/component-layout.css
- src/components/common/input.html
- src/components/common/item-card.html
- src/components/common/product-item.html
- src/components/product-detail-component.html
- src/components/style/product-detail-component.css
- src/page/product-detail.html
- src/page/style/product-detail.css
> [Feat] 상품 상세 페이지 수정 작업

- src/components/common/css/header.css
- src/components/common/css/navbar.css
- src/components/common/js/header.js
- src/components/common/navbar.html
- src/components/itemlist/itemlist-filter.css
- src/page/js/itemlist.js
- src/page/style/itemlist.css
> Modify header/itemlist youngju

- src/common/base.css
- src/components/common/navbar.html
- src/page/style/itemlist.css
- 이미지 경로 수정
- 사이드메뉴, 필터시 바디 스크롤락 클래스 추가
resolves #
> [Modify] 경로 수정 body 클래스 추가

- index.html
- src/components/common/item-card.html
- src/components/findstore/findstore-form.html
- src/page/findstore.html
- src/page/style/customer-service.css
> [Docs] Index페이지에 링크 추가

- index.html
- src/components/common/accrodion.html
> [Feat] 아코디언 접근성 추가

- src/components/itemcard.html
- src/components/style/wishtitle.css
- src/components/wishtitle.html
- src/page/style/wishList.css
- src/page/wishList.html
데스크톱 화면에서 위시리스트 페이지 어느정도 구현해놨고 위시리스트 타이틀에 sticky를 추가해서 스크롤할 때 따라오도록 기능을 구현해놨습니다.
resolves #57
> [Feat] 데스크탑 위시리스트 페이지 구현, 위시리스트 타이틀 배너에 sticky 구현

- src/components/common/css/itemcard.css
- src/components/common/css/wishtitle.css
- src/components/common/itemcard.html
- src/components/common/wishtitle.html
- src/page/style/wishList.css
- src/page/wishList.html
> [Modify] 위시리스트 타이틀 배너 안쪽 여백 값 수정

- src/page/signin.html
- src/page/style/signin.css
로그인 및 비밀번호 입력 폼의 불필요한 `input-wrapper` 래퍼 요소를 제거하고, 스타일을 `input-field`에 직접 적용하여 구조를 단순화했습니다.
- HTML 구조 간결화 (`div.input-wrapper` 제거)
- CSS에서 `.input-wrapper` 관련 스타일 제거 및 `.input-field`에 통합 적용
- 접근성 및 시맨틱 구조 유지 (`label`, `sr-only` 유지)
- 로그인 및 비밀번호 입력 UI는 시각적으로 기존과 동일하게 작동함
resolves #46
> refactor: input-wrapper 제거 및 구조 간소화

- src/components/common/css/header.css
- src/components/common/css/item-card.css
- src/components/common/css/navbar.css
- src/components/common/header.html
- src/components/common/itemcard.html
- src/components/common/navbar.html
- src/components/common/wishtitle.html
- src/components/itemlist/itemlist-header.css
- src/page/customer-service.html
- src/page/findstore.html
- src/page/itemlist.html
- src/page/main.html
- src/page/product-detail.html
- src/page/signin.html
- src/page/signup.html
- src/page/wishList.html
-header, navbar, itemlist 웹 접근성, 키보드 접근성 수정
-navbar 검색창 마크업 수정
-글꼴 link태그 오류 수정
resolves #
> [Refactor] 웹 접근성, 시맨틱 마크업, 문법오류 수정

- src/style.css
index 페이지의 CSS 일부를 리팩토링했습니다.  
작은 화면에서의 텍스트 겹침 문제를 해결하기 위해 `.team-name`의 위치를 조정했습니다.
resolves #104
> refactor: index 페이지 스타일 리팩토링

- src/page/main.html
- [] 버그 수정
- [] 커밋 메시지 컨벤션에 맞게 작성했습니다.
- [] 코딩 컨벤션에 맞게 작성했습니다.
- [] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트).
resolves #8
> [Feat] 코드 수정

- index.html
- src/main.js
- src/style.css
> [Feat] IndexPage 4차

- src/components/main-page.html
- src/components/style/main-page.css
- src/page/main.html
- src/page/style/main.css
- [] CSS 등 사용자 UI 디자인 변경
- [] 커밋 메시지 컨벤션에 맞게 작성했습니다.
- [] 코딩 컨벤션에 맞게 작성했습니다.
- [] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트).
resolves #8
> [Feat] 샵카드 와이드 이미지 border 삭제

- src/page/wishList.html
> [Modify] CSS 파일 가져오는 경로 수정
